package com.example.english_app.ui

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import com.example.english_app.ui.theme.*

// All words below use imageUrl = "" on purpose. CarouselScreen shows a gray
// placeholder box for any word with a blank imageUrl. Once real images are
// added (as drawables), just set the matching imageUrl (e.g. "docword1")
// and add the mapping in CarouselScreen.getImageResId().

// ---------- Document 1: Advanced Vocabulary ----------
val docWords1 = listOf(
    Word("Crouch", "", "To bend low to hide or get ready to move.", "The cat crouched under the bush before catching its prey.", "crouch"),
    Word("Flinch", "", "To move suddenly out of fear or pain.", "Robert flinched when he saw the snake.", "flinch"),
    Word("Limerence", "", "An obsessive desire or infatuation for someone.", "His limerence for the actor grew after watching all his blockbuster movies.", "limerance"),
    Word("Halcyon", "", "Calm, peaceful, and happy.", "I recalled halcyon childhood days.", "doc1_halcyon"),
    Word("Vellichor", "", "The nostalgic feeling of being inside an old bookstore.", "The old book store gives me vellichor.", "vellichor"),
    Word("Ineffable", "", "Too great to be expressed in words.", "The mountain's beauty is ineffable.", "ineffable"),
    Word("Serendipity", "", "A pleasant surprise found by chance.", "I found my lost purse by serendipity.", "serendipity"),
    Word("Poignant", "", "Deeply emotional or touching.", "The climax of the movie is poignant.", "doc1_poignant"),
    Word("Jubilant", "", "Feeling or showing great happiness.", "I felt jubilant after passing in the examinations.", "doc1_jubilant"),
    Word("Equanimity", "", "Calmness and composure, especially in a difficult situation.", "They accepted the demise of their father with equanimity.", "equanimity"),
    Word("Querencia", "", "A place where one feels safe and at home.", "The lawn is my querencia.", "querencia"),
    Word("Dredging", "", "Digging or clearing out to widen a passage.", "Scavengers are dredging the open drainage.", "dredging"),
    Word("Henchman", "", "A loyal follower, especially of a villain.", "The chit fund manager sent his henchmen to collect the pending dues.", "henchman"),
    Word("Brick kiln", "", "A place where bricks are baked.", "Many labourers have been working in the brick kilns.", "brick_klins"),
    Word("Truce", "", "An agreement to stop fighting.", "The two opponent parties signed a truce.", "truce"),
    Word("Clandestine", "", "Kept secret, often because it is illegal.", "Robbers had a clandestine meeting at night.", "clandestine"),
    Word("Disgruntled", "", "Unhappy and annoyed.", "My wife left the house disgruntled after the argument.", "disgruntled"),
    Word("Grappling", "", "Struggling or wrestling with something.", "She is grappling with financial problems.", "grappling"),
    Word("Conclave", "", "A secret or private meeting.", "Leaders met in conclave to discuss the election.", "conclave"),
    Word("Trailblazer", "", "The first person to do or discover something.", "Albert Einstein was a trailblazer in science.", "trailblazer"),
    Word("Pioneer", "", "A person who is among the first to try something new.", "The Wright brothers were pioneers in aviation.", "pioneer"),
    Word("Tweak", "", "To change something slightly.", "She tweaked the whole plan.", "tweak"),
    Word("Ember", "", "A small piece of burning coal or wood.", "My mother blew on the ember to bring the fire back.", "ember"),
    Word("Domicile", "", "A person's permanent home or legal residence.", "Students have to submit domicile proof.", "domicile"),
    Word("Maverick", "", "An independent thinker who does things their own way.", "Gandhi was a maverick leader who chose non-violence instead of war.", "maverick"),
    Word("Whiff", "", "A slight smell carried in the air.", "I caught a whiff of jasmine in the air.", "whiff"),
    Word("Consecration", "", "A sacred ceremony, often at a temple or church.", "The ancient temple was revived with a consecration ceremony.", "consecration_ceremony"),
    Word("Hoax", "", "A false story meant to trick people.", "The story about treasure in the temple was just a hoax.", "hoax"),
    Word("Snollygoster", "", "A selfish, unprincipled politician.", "People should avoid voting for a snollygoster.", "snollygoster"),
    Word("Defenestrate", "", "To throw someone or something out of a window.", "The protesters symbolically defenestrated the leader's portrait.", "defenestrate"),
    Word("Diktat", "", "An order imposed without discussion.", "Employees neglected the management's diktat.", "diktat"),
    Word("Miscreant", "", "A person who behaves badly or breaks the law.", "The miscreants damaged the government transport.", "miscreants"),
    Word("Trespass", "", "To enter someone's property without permission.", "He trespassed on private land.", "tresspass"),
    Word("Broiling day", "", "A very hot, sunny day.", "It was a broiling day.", "broiling"),
    Word("Croon", "", "To sing or hum softly.", "The mother crooned a lullaby.", "croon")
)

// ---------- Document 2: Basic Vocabulary ----------
val docWords2 = listOf(
    Word("Splendid", "", "Very beautiful and impressive.", "The Indian team gave a splendid performance.", "splendid"),
    Word("Elegant", "", "Graceful and stylish.", "Her handwriting is elegant and neat.", "elegant"),
    Word("Swift", "", "Fast.", "The police took swift action to arrest the thief.", "swift"),
    Word("Cozy", "", "Warm and comfortable.", "The room was cozy in winter.", "cozy"),
    Word("Drowsy", "", "Sleepy.", "I felt drowsy after the heavy dinner.", "drowsy"),
    Word("Ponder", "", "To think deeply about something.", "She keeps pondering on her problems.", "ponder"),
    Word("Evade", "", "To escape or avoid.", "The deer evaded the hunter.", "evade"),
    Word("Ephemeral", "", "Lasting for a very short time.", "The beauty of the sunrise is ephemeral.", "ephemeral"),
    Word("Glance", "", "To look quickly.", "She glanced at the wall clock.", "glance"),
    Word("Stare", "", "To look fixedly.", "Ravi stared at Robert in anger.", "stare"),
    Word("Grab", "", "To take suddenly.", "She grabbed my pen.", "grab"),
    Word("Snatch", "", "To take by force.", "The monkey snatched the fruits from my hand.", "snatch"),
    Word("Mumble", "", "To speak unclearly with a half-closed mouth.", "John mumbled the answer because he was shy.", "mumble"),
    Word("Yell", "", "To shout loudly.", "The teacher yelled at him for not completing the assignment.", "yell"),
    Word("Obsolete", "", "Outdated, no longer used.", "Tape recorders are now considered obsolete.", "obsolete"),
    Word("Resilient", "", "Able to recover quickly from difficulties.", "She fell down but was resilient and stood up again.", "resilient"),
    Word("Timid", "", "Shy and nervous.", "She was too timid to answer her teacher.", "timid"),
    Word("Slam", "", "To shut with force.", "Geetha slammed the door with force.", "slam"),
    Word("Groan", "", "To make a low sound of pain.", "The patient groaned in pain.", "groan"),
    Word("Persuade", "", "To convince someone.", "He persuaded his friend to join for higher studies.", "persuade"),
    Word("Reluctant", "", "Unwilling to do something.", "She was reluctant to speak in front of the audience.", "reluctant"),
    Word("Embarrass", "", "To make someone feel shy or uncomfortable.", "I feel embarrassed to speak in front of an audience.", "embarrass"),
    Word("Exaggerate", "", "To describe something as better or worse than it really is.", "He exaggerated his pain to get attention.", "exaggerate"),
    Word("Surly", "", "Rude and bad-tempered.", "She gave a surly look."),
    Word("Slush", "", "Melting snow mixed with mud, in a liquid state.", "Heavy rain changed the green field into slush.", "slush"),
    Word("Sludge", "", "A thick, dirty substance like mud or waste.", "Labourers cleaned the sludge from the water tank.", "sludge"),
    Word("Grime", "", "A layer of dirt that is hard to clean.", "The kitchen loft was covered with grime.", "grime"),
    Word("Devour", "", "To eat something quickly and hungrily.", "She devoured the lunch in two minutes.", "devour"),
    Word("Plunge", "", "To jump or dive suddenly.", "She plunged into the water.", "plunge"),
    Word("Shred", "", "To tear something into small pieces.", "She shredded the old notice in anger.", "shred")
)

// ---------- Document 3: Basic vs Advanced Vocabulary ----------
val docWords3 = listOf(
    Word("Colossal", "", "Advanced form of 'big' — extremely large.", "I saw a colossal statue in the museum.", "collasal"),
    Word("Myriad", "", "Advanced form of 'many' — a huge, countless number.", "My teacher offered a myriad of information.", "many"),
    Word("Ecstatic", "", "Advanced form of 'happy' — overjoyed.", "Priya is ecstatic about her new college.", "ecstatic"),
    Word("Incensed", "", "Advanced form of 'angry' — very angry.", "The teacher was incensed by the team's grave mistake.", "incensed"),
    Word("Amble", "", "Advanced form of 'walk' — to walk slowly and relaxed.", "I like to amble along the riverside.", "ambel"),
    Word("Deplorable", "", "Advanced form of 'bad' — very poor or shocking.", "My friend's hostel was in a deplorable state.", "deplorable"),
    Word("Pristine", "", "Advanced form of 'new' — spotless, in original condition.", "Her desk is always pristine.", "pristine"),
    Word("Venerable", "", "Advanced form of 'old' — respected because of age.", "I visited a venerable church in Venice.", "venerable"),
    Word("Perpetually", "", "Advanced form of 'always' — constantly, without stopping.", "My friend is perpetually worried about her examination.", "perpetually"),
    Word("Reticent", "", "Advanced form of 'quiet' — reserved, not saying much.", "Vijay is reticent about the recent issue.", "reticent"),
    Word("Notion", "", "Advanced form of 'idea' — a belief or plan.", "My friend has a notion to travel abroad.", "notion"),
    Word("Perplexing", "", "Advanced form of 'confusing' — very puzzling.", "Her idea was perplexing.", "perplexing"),
    Word("Petrified", "", "Advanced form of 'scared' — frozen with fear.", "He was petrified at the sight of a lion in front of him.", "petrified"),
    Word("Dine", "", "Advanced form of 'eat' — to eat a meal, usually formally.", "They decided to dine at a multi-cuisine restaurant.", "dine"),
    Word("Recurrently", "", "Advanced form of 'often' — happening again and again.", "He lost his job as he made mistakes recurrently.", "recurrently"),
    Word("Sporadically", "", "Advanced form of 'sometimes' — occurring at irregular intervals.", "I go to that hotel sporadically.", "sporadically"),
    Word("Amiable", "", "Advanced form of 'nice' — friendly and pleasant.", "She has a most amiable personality.", "amiable"),
    Word("Meager", "", "Advanced form of 'little' — very small in amount.", "People got meager food after the disaster.", "meager"),
    Word("Apprehensive", "", "Advanced form of 'nervous' — anxious about something.", "She felt apprehensive about presenting the seminar.", "apprensive"),
    Word("Tenuous", "", "Advanced form of 'weak' — flimsy, barely valid.", "They presented tenuous evidence.", "tenuous"),
    Word("Tardy", "", "Advanced form of 'late' — slow to arrive or act.", "The student was marked tardy for arriving after the bell.", "tardy"),
    Word("Bestow", "", "Advanced form of 'give' — to formally present something.", "The father bestowed his blessings on his newborn child.", "bestow"),
    Word("Craft", "", "Advanced form of 'make' — to skillfully create.", "She crafts beautiful jewellery from gold.", "craft"),
    Word("Lucid", "", "Advanced form of 'clear' — easy to understand.", "Her essay is lucid in style.", "lucid"),
    Word("Imminently", "", "Advanced form of 'soon' — about to happen very shortly.", "The examinations will commence imminently.", "imminently"),
    Word("Discourteous", "", "Advanced form of 'rude' — impolite.", "The guest was discourteous to all.", "discourteous"),
    Word("Engrossed", "", "Advanced form of 'busy' — fully absorbed in something.", "She was engrossed in her video call.", "engrossed"),
    Word("Surmise", "", "Advanced form of 'guess' — to conclude from limited evidence.", "I surmise he forgot to take his tablet.", "surmise"),
    Word("Cogitate", "", "Advanced form of 'think' — to think deeply.", "She cogitated on the issue deeply.", "cogitate"),
    Word("Obstinate", "", "Advanced form of 'stubborn' — unwilling to change one's mind.", "She is obstinate in negotiations.", "obsient"),
    Word("Negligent", "", "Advanced form of 'careless' — failing to take proper care.", "The security guard was negligent in his duty.", "negligence"),
    Word("Turmoil", "", "Advanced form of 'trouble' — a state of great disturbance.", "The city was in turmoil after the political rally.", "turmoil"),
    Word("Altercation", "", "Advanced form of 'fight' — a noisy argument.", "He had an altercation while bargaining.", "altercation"),
    Word("Vivid", "", "Advanced form of 'bright' — intensely colorful.", "She painted using vivid colours.", "vivid"),
    Word("Meander", "", "Advanced form of 'wander' — to move slowly with no fixed direction.", "She meandered in the hills.", "mander")
)

// ---------- Document 4: Blended Vocabulary ----------
val docWords4 = listOf(
    Word("Brunch", "", "Breakfast + Lunch.", "I had brunch at 11.00 a.m.", "doc4_brunch"),
    Word("Smog", "", "Smoke + Fog.", "The area was covered with smog after the fire.", "doc4_smog"),
    Word("Motel", "", "Motor + Hotel.", "I stayed in a motel during our trip.", "doc4_motel"),
    Word("Chortle", "", "Chuckle + Snort.", "He chortled while watching the comedy movie.", "doc4_chortle"),
    Word("Spork", "", "Spoon + Fork.", "She used a spork to eat noodles and drink soup.", "spork"),
    Word("Blog", "", "Web + Log.", "I wrote a blog about my summer vacation.", "doc4_blog"),
    Word("Infomercial", "", "Information + Commercial.", "Local channels are telecasting a 30 minute infomercial on kitchen gadgets.", "infomercial"),
    Word("Frenemy", "", "Friend + Enemy.", "Lucy and Riya are frenemies who always compete.", "doc4_frenemy"),
    Word("Chillax", "", "Chill + Relax.", "My friend wanted to chillax over the weekend.", "doc4_chillax"),
    Word("Guesstimate", "", "Guess + Estimate.", "My father gave a guesstimate of how many relatives would come.", "guesstimate"),
    Word("Workaholic", "", "Work + Alcoholic.", "Ruby is a workaholic who even works in late evenings.", "workaholic"),
    Word("Shopaholic", "", "Shop + Alcoholic.", "She is a shopaholic who goes shopping every day.", "shopaholic"),
    Word("Sitcom", "", "Situation + Comedy.", "During hard days, a sitcom will cheer you up.", "sitcom"),
    Word("Edutainment", "", "Education + Entertainment.", "The kids' podcast is a great piece of edutainment.", "edutainment"),
    Word("Podcast", "", "iPod + Broadcast.", "Nowadays, people listen to podcasts every morning.", "podcast"),
    Word("Biopic", "", "Biography + Picture.", "The biopic on the political leader was inspiring.", "biopic"),
    Word("Emoticon", "", "Emotion + Icon.", "My friend added a crying emoticon to her text message.", "emoticon"),
    Word("Staycation", "", "Stay + Vacation.", "I enjoyed a staycation exploring local places.", "staycation"),
    Word("Infotainment", "", "Information + Entertainment.", "The interview with the entrepreneur was a kind of infotainment.", "infotainment"),
    Word("Electrocute", "", "Electric + Execute.", "Two people were electrocuted when they touched the wire.", "electocute"),
    Word("Linner", "", "Lunch + Dinner.", "I missed lunch, so I had linner at 4.30 p.m.", "linner"),
    Word("Netiquette", "", "Internet + Etiquette.", "Everyone should follow netiquette while emailing.", "netiquette"),
    Word("Jeggings", "", "Jeans + Leggings.", "She likes to wear jeggings that look like jeans.", "jeggings"),
    Word("Dramedy", "", "Drama + Comedy.", "I watched an interesting dramedy on TV.", "dramedy"),
    Word("Listicle", "", "List + Article.", "I read a listicle in the newspaper.", "listicle"),
    Word("Pixel", "", "Picture + Element.", "I bought a mobile phone with a good pixel count.", "pixel"),
    Word("Interpol", "", "International + Police.", "Interpol officers helped catch the smugglers who fled abroad.", "interpol"),
    Word("Camcorder", "", "Camera + Recorder.", "The photographer used a camcorder at my daughter's wedding.", "camcorder"),
    Word("Niftastic", "", "Nifty + Fantastic.", "Your new dress is really niftastic.", "niftastic"),
    Word("Cremains", "", "Cremation + Remains.", "My mother's cremains were scattered in the river as part of the ritual.", "cremains"),
    Word("Fortnight", "", "Fourteen + Night.", "I have planned to finish my work in a fortnight.", "fortnight"),
    Word("Mockumentary", "", "Mock + Documentary.", "Students made a mockumentary about teachers for Teachers' Day.", "mockumentary"),
    Word("Nibling", "", "Niece/Nephew + Sibling.", "I visited my niblings last week.", "niblings"),
    Word("Phablet", "", "Phone + Tablet.", "She bought a new phablet.", "phablet"),
    Word("Flexitarian", "", "Flexible + Vegetarian.", "My friend is a flexitarian who eats egg sometimes.", "flexitarian")
)

// ---------- Document 5: Kitchen Vocabulary ----------
val docWords5 = listOf(
    Word("Sauté", "", "Cooking in a pan with oil over medium to high heat.", "Onions are sautéed until they turn golden brown.", "saute"),
    Word("Whisk", "", "To beat ingredients quickly to add air.", "I whisked the eggs to make an omelet.", "doc5_whisk"),
    Word("Knead", "", "To work dough by hand to develop gluten.", "She kneads wheat flour to make chapati.", "doc5_knead"),
    Word("Grate", "", "To shred food into small pieces.", "I grated coconut for chutney.", "doc5_grate"),
    Word("Mash", "", "To crush food into a soft mass.", "I gave mashed bananas to my baby.", "doc5_mash"),
    Word("Blanch", "", "To boil food briefly and then cool it quickly.", "She blanched tomatoes before peeling.", "doc5_blanch"),
    Word("Tongs", "", "A tool used to handle hot vessels or food.", "I used tongs to lift the hot utensils.", "doc5_tongs"),
    Word("Mortar and Pestle", "", "A stone tool used for grinding.", "My grandmother used a mortar and pestle to grind batter for idli.", "doc5_mortar_pestle"),
    Word("Ladle", "", "A deep spoon used to serve curry or soup.", "The chef used a ladle to serve soup into bowls.", "doc5_ladle"),
    Word("Sieve", "", "A tool used to remove lumps or solids from a liquid or powder.", "She used a sieve to remove stones from the wheat flour.", "sieve"),
    Word("Colander", "", "A bowl-shaped tool used to drain rice or vegetables.", "He used a colander to drain water from the boiled noodles.", "colander"),
    Word("Wok", "", "A deep, round frying pan (kadaai).", "I fried fish in a wok.", "wok"),
    Word("Casserole", "", "A dish used to cook and serve food.", "I prepared and served vegetable rice in a casserole.", "casserole"),
    Word("Degustation Menu", "", "A tasting menu that showcases a chef's skill.", "The newly opened restaurant offers a degustation menu.", "degustation_menu"),
    Word("Foxtail Millet", "", "A type of nutritious millet.", "Foxtail millet is used by many people for its nutritional value.", "foxtail"),
    Word("Lentils", "", "Round legumes, used to make dal.", "Lentils are widely used across India in the form of dal.", "lentils"),
    Word("Black gram", "", "A type of pulse used in South Indian cooking.", "Black gram is used to make dosa batter.", "black_gram"),
    Word("Green gram", "", "A green-colored pulse rich in vitamins.", "Green gram is used to make sprouts.", "green_gram"),
    Word("Cumin", "", "An aromatic spice.", "Cumin seeds have a strong aroma.", "cumin"),
    Word("Fennel Seeds", "", "An aromatic seed often used as a mouth freshener.", "Fennel seeds are consumed after food as a mouth freshener.", "fennel_seeds"),
    Word("Fenugreek Seeds", "", "A bitter-tasting spice used in cooking and medicine.", "Fenugreek seeds are used in cooking and medicine.", "fenugreek_seeds"),
    Word("Mustard seeds", "", "A small seed used for seasoning.", "Mustard seeds crackle in hot oil.", "mustard_seeds"),
    Word("Cloves", "", "An aromatic spice, also used medicinally.", "Cloves are used to get relief from a toothache.", "cloves"),
    Word("Cardamom", "", "A fragrant spice used in sweets and tea.", "Cardamom is used in tea for its aromatic flavour.", "cardamom"),
    Word("Cinnamon", "", "A spice made from dried tree bark.", "Cinnamon is used to make desserts.", "cinnamon"),
    Word("Parsley", "", "An aromatic leafy herb.", "Parsley is used for garnishing food.", "parsley"),
    Word("Bay leaves", "", "Aromatic leaves used to flavor food.", "Bay leaves are used while preparing biryani.", "bay_leaves"),
    Word("Poppy seeds", "", "Small seeds added for a nutty flavor.", "Poppy seeds are used to prepare curries.", "poppy_seeds"),
    Word("Asafoetida", "", "A strong-smelling spice that aids digestion.", "Asafoetida is commonly used in Indian cooking to improve digestion.", "asafoetida"),
    Word("Sesame", "", "A small, oil-rich seed used in sweets.", "Sesame is used in sweets and savouries.", "sesame")
)

// ---------- Document 6: Movement Vocabulary ----------
val docWords6 = listOf(
    Word("Wink", "", "To close and open one eye quickly, often as a signal.", "She winked at her friend.", "wink"),
    Word("Chew", "", "To crush food with the teeth before swallowing.", "My friend chews the food slowly.", "chew"),
    Word("Blink", "", "To close and open both eyes quickly.", "They blinked their eyes in surprise.", "blink"),
    Word("Blow your nose", "", "To force air through the nose to clear it.", "She blows her nose gently when she gets a cold.", "blow_your_nose"),
    Word("Sneeze", "", "To suddenly expel air through the nose and mouth.", "Raghu sneezed loudly.", "sneeze"),
    Word("Giggle", "", "To laugh lightly.", "Students giggle at funny jokes made by the teacher.", "giggle"),
    Word("Snap fingers", "", "To make a sharp sound by flicking the fingers.", "I snapped my fingers to get my sister's attention.", "snap_fingers"),
    Word("Nod", "", "To move the head up and down, often to agree.", "Students nod their heads while listening in class.", "nod"),
    Word("Cup ears", "", "To place hands behind the ears to hear better.", "He cupped his ears to hear better in a noisy place.", "cup_ear"),
    Word("Yank", "", "To pull something suddenly and hard.", "Robert yanked open the window.", "yank"),
    Word("Poke", "", "To jab someone or something with a finger.", "My friend poked me playfully.", "poke"),
    Word("Leap", "", "To jump a long way or with force.", "My friend leaped over the puddle.", "leap"),
    Word("Flick", "", "To move something with a quick, light movement.", "John flicks the fan switch.", "flick"),
    Word("Tickle", "", "To touch lightly to cause laughter.", "The child laughs when I tickle him.", "tickle"),
    Word("Shrug", "", "To raise the shoulders to show doubt or indifference.", "He shrugs his shoulders to show his disapproval.", "shrugs"),
    Word("Hop", "", "To jump on one or both feet.", "He hops on the ground.", "hop"),
    Word("Lean", "", "To bend or rest against something.", "Charles leans on his chair to rest.", "lean"),
    Word("Sigh", "", "To breathe out slowly, showing relief or sadness.", "She gives a sigh of relief.", "sigh"),
    Word("Stutter", "", "To speak with involuntary pauses or repeated sounds.", "The child stuttered while speaking to a stranger.", "stutter"),
    Word("Facepalm", "", "To cover the face with the hand out of frustration.", "He did a facepalm after realizing his mistake.", "facepalm"),
    Word("Burp", "", "To release air from the stomach through the mouth.", "He gave a burp after a heavy lunch.", "burp"),
    Word("Slurp", "", "To drink or eat noisily.", "My friend slurped the coffee loudly.", "slurp"),
    Word("Sniff", "", "To breathe in through the nose to smell something.", "The police dogs sniff to find clues.", "sniff"),
    Word("Flutter", "", "To move wings or fabric quickly and lightly.", "The butterfly fluttered its wings beautifully.", "flutter"),
    Word("Peer", "", "To look closely or carefully.", "The officials peered at the fingerprints closely.", "peer"),
    Word("Grimace", "", "To twist the face in pain or disgust.", "The baby grimaced at the sight of the injection.", "grimance"),
    Word("Pout", "", "To push out the lips, showing displeasure.", "The kid began to pout when taken to school.", "pout"),
    Word("Wince", "", "To make a slight facial expression of pain.", "James winced when he noticed his friend's wound."),
    Word("Gargle", "", "To rinse the throat with liquid, keeping the head tilted back.", "I gargle with hot water to soothe a sore throat.", "gargle"),
    Word("Hiccup", "", "A sudden, involuntary breathing spasm.", "She ate too quickly and got hiccups.", "hiccup"),
    Word("Climb", "", "To move upward using hands and feet.", "Children climbed trees to play.", "climb"),
    Word("Crawl", "", "To move slowly on hands and knees.", "The baby crawled towards his father.", "crawl"),
    Word("Slap", "", "To hit with an open hand.", "She slapped her sister in anger.", "slap"),
    Word("Squeeze", "", "To press something firmly.", "My daughter squeezed the lemon to make fresh juice.", "squeeze"),
    Word("Squash", "", "To crush something flat.", "I squashed the tomato.", "squash"),
    Word("Crumple", "", "To crush into creases or folds.", "He crumpled the waste paper.", "crumple"),
    Word("Wring", "", "To twist and squeeze to remove liquid.", "I wring a wet towel before hanging it out to dry.", "wring"),
    Word("Spill", "", "To cause liquid to flow out accidentally.", "I spilled the milk in the kitchen.", "spill"),
    Word("Spit", "", "To force saliva out of the mouth.", "Avoid spitting in public places.", "spit"),
    Word("Slouch", "", "To sit, stand, or move with a bent, lazy posture.", "Students are slouching inside the classroom.", "slouch")
)

// ---------- Document 7: Vocab Twist (Homographs) ----------
val docWords7 = listOf(
    Word("Bat", "", "1) A flying mammal. 2) A stick used in sports like cricket.", "I saw a bat on the tree. / I got Dhoni's signature on my cricket bat.", "bat"),
    Word("Bank", "", "1) Where people save and borrow money. 2) The land alongside a river.", "I am going to the bank to deposit money. / She went to the river bank to relax.", "bank"),
    Word("Bark", "", "1) The sound a dog makes. 2) The outer layer of a tree.", "The dog barks at the thief. / Priya carved her name on the bark of the tree.", "bark"),
    Word("Bow", "", "1) To bend forward. 2) A weapon used to shoot arrows.", "The actors bowed to the audience. / The hunter aimed the bow at the deer.", "bow"),
    Word("Fair", "", "1) Morally right. 2) An exhibition.", "It is not fair to be partial towards any student. / There is a job fair on our campus today.", "fair"),
    Word("Jam", "", "1) A sweet fruit spread. 2) To get stuck or blocked.", "I love strawberry jam on toast. / The traffic jam made me late for work.", "jam"),
    Word("Lead", "", "1) To guide or direct. 2) A type of metal.", "She will lead the team in the project. / Pipes were once made of lead.", "lead"),
    Word("Match", "", "1) A contest or game. 2) A stick used to start a fire.", "The football match was very exciting. / He struck a match to light the candle.", "match"),
    Word("Spring", "", "1) The season after winter. 2) A coiled device that can stretch back.", "Flowers bloom in spring. / The mattress has a broken spring inside.", "spring"),
    Word("Tire", "", "1) To feel exhausted. 2) The rubber covering of a wheel.", "Long walks tire me out. / The car needs a new tire.", "tire"),
    Word("Current", "", "1) The flow of electricity or water. 2) Happening now.", "The current in the river was strong. / He is not satisfied with his current job.", "current"),
    Word("Minute", "", "1) A unit of time. 2) Extremely small.", "Wait a minute, please. / The insect was minute, barely visible.", "minute"),
    Word("Scale", "", "1) The outer covering of a fish. 2) A system used to measure.", "The fish's scale shimmered in the sun. / We used a scale to weigh the vegetables.", "scale"),
    Word("Clip", "", "1) To cut something short. 2) A small device used to hold things together.", "He clipped the hedge neatly. / She used a clip to hold her hair.", "clip"),
    Word("Bolt", "", "1) To run away suddenly. 2) A metal bar used to lock something.", "The horse bolted at the sound of thunder. / He slid the bolt to lock the gate.", "bolt"),
    Word("Charge", "", "1) To ask a price. 2) To rush forward.", "The shop charges extra for delivery. / The bull charged at the fence.", "charge"),
    Word("Pitch", "", "1) The tone of a sound. 2) To throw something.", "Her voice has a high pitch. / He pitched the ball to the batsman.", "pitch"),
    Word("Console", "", "1) To comfort someone. 2) A control panel.", "She tried to console her crying friend. / He pressed the buttons on the game console.", "console"),
    Word("Pound", "", "1) To hit repeatedly. 2) A unit of weight.", "He pounded on the door. / The parcel weighs two pounds.", "pound"),
    Word("Suspend", "", "1) To hang something from above. 2) To stop something temporarily.", "The lamp was suspended from the ceiling. / The match was suspended due to rain.", "suspend"),
    Word("Plot", "", "1) A secret plan. 2) A piece of land.", "The villains hatched a plot. / They bought a plot to build a house.", "plot"),
    Word("Monitor", "", "1) To observe carefully. 2) A screen.", "Teachers monitor the students during exams. / He bought a new computer monitor.", "monitor"),
    Word("Anchor", "", "1) An object that keeps a ship in place. 2) A news presenter.", "The ship dropped its anchor. / She works as a news anchor.", "anchor"),
    Word("Appraise", "", "1) To evaluate the value of something. 2) To judge the quality of something.", "The jeweler appraised the necklace. / The manager appraised his employee's work.", "appraise"),
    Word("Abstract", "", "1) Existing in thought but not physical. 2) To remove.", "Freedom is an abstract idea. / The chemist abstracted the sample for testing."),
    Word("Racket", "", "1) A loud, disturbing noise. 2) A dishonest scheme.", "The children made a racket upstairs. / The police busted an illegal racket.", "racket"),
    Word("Vault", "", "1) A secured room, often for valuables. 2) To jump over something.", "The gold was kept in a bank vault. / The athlete vaulted over the bar.", "vault"),
    Word("Alight", "", "1) To get down from a vehicle. 2) To be on fire.", "Passengers alight at the next stop. / The dry grass was alight within seconds.", "alight"),
    Word("Annotate", "", "1) To add notes to something. 2) To explain with notes.", "She annotated the textbook with her own notes. / The teacher annotated the essay with feedback.", "annotate"),
    Word("Conflate", "", "1) To combine two things into one. 2) To mistakenly treat as the same.", "The report conflates two separate issues. / People often conflate the two festivals.", "conflate"),
    Word("Cower", "", "1) To crouch down in fear. 2) To show fear openly.", "The dog cowered during the storm. / He cowered before his angry boss.", "cower"),
    Word("Dissipate", "", "1) To scatter and disappear. 2) To waste resources.", "The morning fog dissipated by noon. / He dissipated his fortune on gambling.", "dissipate"),
    Word("Enervate", "", "1) To weaken someone. 2) To make someone feel tired.", "The long illness enervated him. / The heat enervated the entire team.", "enervate"),
    Word("Connive", "", "1) To secretly cooperate in a wrongdoing. 2) To ignore a wrongdoing on purpose.", "The two officials connived to hide the fraud. / The guard connived at the theft.")
)

val docCategories = listOf(
    Category("doc1", "Advanced Vocabulary", "Rich, expressive words for advanced learners", VibrantPurple, Icons.Default.AutoStories, docWords1),
    Category("doc2", "Basic Vocabulary", "Everyday words to build a strong foundation", VibrantTeal, Icons.Default.MenuBook, docWords2),
    Category("doc3", "Basic vs Advanced", "Simple words paired with their advanced equivalents", VibrantOrange, Icons.Default.CompareArrows, docWords3),
    Category("doc4", "Blended Words", "Portmanteau words formed by blending two words", VibrantPink, Icons.Default.Shuffle, docWords4),
    Category("doc5", "Kitchen Vocabulary", "Cooking tools, spices, and kitchen terms", VibrantGreen, Icons.Default.Kitchen, docWords5),
    Category("doc6", "Movement Vocabulary", "Words describing small actions and gestures", VibrantBlue, Icons.Default.DirectionsRun, docWords6),
    Category("doc7", "Vocab Twist", "Homographs — one word, multiple meanings", VibrantYellow, Icons.Default.SwapHoriz, docWords7)
)
